name: GitHub Pages

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 15 * * *' #2pm german time

  workflow_dispatch:

jobs:
      deploy:
        runs-on: ubuntu-22.04
        
        permissions:
          contents: read 
          pages: write
          id-token: write

        environment:
          name: github-pages
          url: "killer4563782.github.io/Enigma/"

        steps:
          - uses: actions/checkout@v3
    
          - name: Checkout Repository
            uses: actions/checkout@v3
            with:
              path: '.'
    
          - name: Set up git-cliff
            uses: kenji-miyake/setup-git-cliff@v1
    
          - run: rm .gitignore
    
          - name: Deploy
            uses: peaceiris/actions-gh-pages@v3
            with:
              publish_dir: ./
              force_orphan: true
